In [1]:
import numpy as np

In [7]:
A = np.random.randint(0, 10, (4, 3))
B = np.random.randint(0, 10, (5, 3))
C = np.random.randint(0, 10, (6, 3))

In [8]:
print(A)
print(B)
print(C)

[[4 6 2]
 [1 0 2]
 [2 5 5]
 [6 1 6]]
[[2 5 7]
 [7 2 1]
 [2 8 7]
 [0 6 3]
 [3 3 4]]
[[2 8 3]
 [5 7 5]
 [5 0 6]
 [5 9 4]
 [8 3 2]
 [5 6 8]]


In [9]:
D = np.einsum('il, jl, kl -> ijkl', A, B, C)

In [11]:
D.shape

(4, 5, 6, 3)

In [16]:
n = 10
m = 4
rank_l = 3
rank_r = 3
op_pre = np.random.randint(0, 10, (n, n, n, rank_l * m * rank_r))
print(op_pre.shape)
op = np.zeros(op_pre.shape[:-1]+op_pre.shape[:-1])
op_dim = op.shape
print(op.shape)
op = op.reshape((op_dim[0]*op_dim[1]*op_dim[2], op_dim[3]*op_dim[4]*op_dim[5]))
print(op.shape)
op = np.vstack([op, np.zeros(op.shape[0])[None,:]])
print(op.shape)
op = np.hstack([op, np.zeros(op.shape[0])[:,None]])
print(op.shape)

(10, 10, 10, 36)
(10, 10, 10, 10, 10, 10)
(1000, 1000)
(1001, 1000)
(1001, 1001)


In [18]:
print(op_pre.shape)
op_pre = op_pre.reshape((op_dim[0]*op_dim[1]*op_dim[2], op_pre.shape[-1]))
print(op_pre.shape)
op_final = np.tensordot(op_pre, op_pre, axes=((1),(1)))
print(op_final.shape)

(1000, 36)
(1000, 36)
(1000, 1000)
