In [1]:
import numpy as np

In [4]:
def poly(x, degree=2):
    return np.array([x**(i+1) for i in range(degree)]).T

In [13]:
x1 = np.array([0.1, 0.2])
x2 = np.array([0.2, 0.3])
x3 = np.array([0.1, 0.3])

d = 2
px1 = poly(x1, degree=d)
px2 = poly(x2, degree=d)
px3 = poly(x3, degree=d)

print(px1.shape, px2.shape, px3.shape)
x1, px1, x2, px2, x3, px3

(2, 2) (2, 2) (2, 2)


(array([0.1, 0.2]),
 array([[0.1 , 0.01],
        [0.2 , 0.04]]),
 array([0.2, 0.3]),
 array([[0.2 , 0.04],
        [0.3 , 0.09]]),
 array([0.1, 0.3]),
 array([[0.1 , 0.01],
        [0.3 , 0.09]]))

In [9]:
batch1 = np.array([px1[0], px2[0], px3[0]])
batch2 = np.array([px1[1], px2[1], px3[1]])

print(batch1.shape, batch2.shape) # batch, degree
batch1, batch2

(3, 2) (3, 2)


(array([[0.1 , 0.01],
        [0.2 , 0.04],
        [0.1 , 0.01]]),
 array([[0.2 , 0.04],
        [0.3 , 0.09],
        [0.3 , 0.09]]))

In [71]:
A = np.array([1, 0, 0, 1]).reshape(-1, 2)
B = np.array([1, 0, 0, -1]).reshape(-1, 2)
C = np.array([0, 1, 1, 0]).reshape(-1, 2)

A, B, C

(array([[1, 0],
        [0, 1]]),
 array([[ 1,  0],
        [ 0, -1]]),
 array([[0, 1],
        [1, 0]]))

In [74]:
print(px1[0][0]*px1[1][0] + px1[0][1]*px1[1][1])
print(px1[0][0]*px1[1][0] - px1[0][1]*px1[1][1])
print(px1[0][0]*px1[1][1] + px1[0][1]*px1[1][0])
px1


0.020400000000000005
0.019600000000000003
0.006000000000000002


array([[0.1 , 0.01],
       [0.2 , 0.04]])

In [80]:
print(batch1[0].T @ A @ batch2[0])
print(batch1[1].T @ B @ batch2[1])
print(batch1[2].T @ C @ batch2[2])

0.020400000000000005
0.0564
0.012


In [81]:
print(np.einsum('i,ij,j->', batch1[0], A, batch2[0]))
print(np.einsum('i,ij,j->', batch1[1], B, batch2[1]))
print(np.einsum('i,ij,j->', batch1[2], C, batch2[2]))

0.020400000000000005
0.0564
0.012


In [82]:
Op = np.array([A, B, C])
Op.shape, batch1.shape, batch2.shape

((3, 2, 2), (3, 2), (3, 2))

In [83]:
np.einsum('ijk,ij,ik->i', Op, batch1, batch2)

array([0.0204, 0.0564, 0.012 ])